export const roles = ["full_access", "can_view", "can_edit"];
export const create_roles = ["full_access", "can_edit"];
export const access_roles = ["full_access"];
export const FULL_ACCESS = "full_access";
export const CAN_VIEW = "can_view";
export const CAN_EDIT = "can_edit";
export const REMOVE_ACCESS = "remove_access";

export const HTTP_RESPONSE_CODE = {
  NOT_FOUND: 404,
  FORBIDDEN: 403,
  CREATED: 201,
  CONFLICT: 409,
  BAD_REQUEST: 400,
  SUCCESS: 200,
  UNAUTHORIZED: 401,
  UNPROCESSABLE_ENTITY: 422,
  SERVER_ERROR: 500,
};

export const enum HttpStatusCode {
  NOT_FOUND = 404,
  CREATED = 201,
  CONFLICT = 409,
  BAD_REQUEST = 400,
  SUCCESS = 200,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  UNPROCESSABLE_ENTITY = 422,
}

export const APP_ERROR_MESSAGE = {
  serverError: "Something went wrong, We are fixing it asap :)",
};

// A simple keyword-based sentiment analysis
export const positiveKeywords = [
  // GitHub Issues / Jira Tickets
  "Bug fix",
  "New feature",
  "Improvement",
  "Resolved",
  "In progress",
  "To do",
  "High priority",
  "Critical issue",
  "Ready for development",
  "Ready for QA",
  "In testing",
  "In review",
  "Completed",
  "Under development",
  "Assigned",
  "Confirmed",
  "Verified",
  "To be implemented",
  "Hotfix",
  "Released",
  "Merged",
  "Pull request",
  "Approved",
  "Scheduled",
  "Functional requirement",
  "Test case passed",
  "Production ready",
  "Live issue",
  "Deployed",
  "Patch available",

  // Development Lifecycle / SRS / Requirements
  "Approved",
  "Signed off",
  "Functional",
  "Detailed design",
  "Well-defined requirements",
  "Finalized",
  "Confirmed requirements",
  "Scheduled for release",
  "Actionable",
  "High impact",
  "Verified in production",
  "Tested",
  "Aligned with goals",
  "Implemented",
  "Feasible",
  "Scalable solution",
  "Performance improvement",
  "Optimized",
  "Meeting acceptance criteria",
  "On track",
  "Validated",
  "Deliverable",
  "User-approved",
  "Ready for release",
  "Release candidate",
  "Confirmed by stakeholders",
  "Production-ready",
  "Aligned with roadmap",
  "Achievable",
  "Roadmap item",
  "Aligned with SRS",
  "Use case addressed",
  "Requirement met",
  "Test case passed",
  "Deployment planned",
];

export const negativeKeywords = [
  // GitHub Issues / Jira Tickets
  "Invalid",
  "Won't fix",
  "Duplicate",
  "Not reproducible",
  "By design",
  "Obsolete",
  "Out of scope",
  "Unassigned",
  "Closed without fix",
  "Can't reproduce",
  "Non-issue",
  "Deferred",
  "Rejected",
  "Ignored",
  "Non-priority",
  "Pending review",
  "Postponed",
  "Low impact",
  "Minor bug",
  "Information only",
  "Resolved without action",
  "Not relevant",
  "No further action",
  "User error",
  "Stale",
  "Won't implement",
  "Incomplete data",
  "Needs clarification",
  "No changes required",
  "Question/Inquiry",
  "Invalid request",
  "Not a bug",
  "Enhancement request",
  "Test issue",
  "Misconfiguration",
  "Configuration issue",
  "Working as expected",
  "Outside SLA",
  "Low risk",
  "Outdated",
  "Not reproducible in latest version",
  "Archived",

  // Development Lifecycle / SRS / Requirements
  "Draft",
  "Unapproved",
  "Pending approval",
  "In discussion",
  "Under review",
  "Concept stage",
  "Non-functional",
  "Low priority",
  "Backlog",
  "Future release",
  "Experimental",
  "To be determined",
  "Exploratory",
  "Potential enhancement",
  "Unclear requirements",
  "Not enough details",
  "Pending requirements",
  "Unconfirmed",
  "Unverified",
  "Proposed",
  "For future consideration",
  "Initial draft",
  "Not scheduled",
  "Unplanned",
  "Optional",
  "Outdated requirements",
  "Non-actionable",
  "Hypothetical",
  "Wishlist",
  "Idea stage",
  "Brainstorming",
  "Research needed",
  "Under investigation",
  "Scoping phase",
  "Feasibility check",
  "Preliminary analysis",
  "Unprioritized",
  "To be scoped",
];
